const CAMPAIGN_MAP = {
    "31": "PAGA - 50% OFF 2X",
    "30": "PAGA - PRIMEIRA À R$50,00 (OU ISENTO)",
    "29": "Troca de titularidade",
    "28": "ISENTA - 50% OFF NA PRIMEIRA MENSALIDADE",
    "27": "ISENTA - INDICAÇÃO",
    "26": "PAGA - R$50,00 OFF 3x",
    "25": "ISENTA - 3 COMPROVANTES DE PGTO",
    "24": "PAGA - R$50,00 OFF 2X",
    "23": "PAGA - SEM DESCONTOS",
    "22": "ISENTA - CONSULTA CPF",
    "21": "ISENTA + 1º PAGAMENTO FEVEREIRO",
    "20": "ISENTA + PAGAMENTO EM JAN",
    "19": "EMPRESARIAL - SEM DESCONTOS",
    "18": "PRIMEIRO PGTO EM JAN - COM TAXA",
    "17": "ISENTA - SEM DESCONTOS",
    "16": "PAGA + 50% OFF 3X",
    "15": "ISENTA + 50% OFF 3X",
    "14": "50% DESC 2 PRIMEIRAS MENSALIDADES",
    "13": "SEMANA DO CONSUMIDOR",
    "12": "NATAL SOLIDÁRIO",
    "11": "BLACK FRIDAY 50% + ISENTA",
    "10": "BLACK FRIDAY ISENTA",
    "8": "BLACK FRIDAY CASHBACK",
    "7": "Isenta Promocional",
    "6": "Colaborador VPU",
    "5": "Negociação",
    "4": "Aniversário 2024",
    "3": "Melhor Plano Net",
    "2": "Campanha Cash Back",
    "0": "Não preenchido"
}