const CAMPAIGN_MAP = {
    "32": "RESGATE PROMOCIONAL",
    "31": "TAXA PAGA - 50% OFF 2X",
    "30": "TAXA PAGA - PRIMEIRA À R$50,00 (OU ISENTO)",
    "29": "Troca de titularidade",
    "28": "TAXA ISENTA - 50% OFF NA PRIMEIRA MENSALIDADE",
    "27": "TAXA ISENTA - INDICAÇÃO",
    "26": "TAXA PAGA - R$50,00 OFF 3x",
    "25": "TAXA ISENTA - 3 COMPROVANTES DE PGTO",
    "24": "TAXA PAGA - R$50,00 OFF 2X",
    "23": "TAXA PAGA - SEM DESCONTOS",
    "22": "TAXA ISENTA - CONSULTA CPF",
    "21": "TAXA ISENTA + 1º PAGAMENTO FEVEREIRO",
    "20": "TAXA ISENTA + PAGAMENTO EM JAN",
    "19": "TAXA EMPRESARIAL - SEM DESCONTOS",
    "18": "PRIMEIRO PGTO EM JAN - COM TAXA",
    "17": "TAXA ISENTA - SEM DESCONTOS",
    "16": "TAXA PAGA + 50% OFF 3X",
    "15": "TAXA ISENTA + 50% OFF 3X",
    "14": "50% DESC 2 PRIMEIRAS MENSALIDADES",
    "13": "SEMANA DO CONSUMIDOR",
    "12": "NATAL SOLIDÁRIO",
    "11": "BLACK FRIDAY 50% + TAXA ISENTA",
    "10": "BLACK FRIDAY TAXA ISENTA",
    "8": "BLACK FRIDAY CASHBACK",
    "7": "Taxa Isenta Promocional",
    "6": "Colaborador VPU",
    "5": "Negociação",
    "4": "Aniversário 2024",
    "3": "Melhor Plano Net",
    "2": "Campanha Cash Back",
    "0": "Não preenchido"
}