const CHANNEL_MAP = {
    "0": "Sem registro",
    "1": "Venda externa/folder",
    "2": "Google",
    "7": "Feiras/Eventos Externos",
    "9": "Indicação de cliente",
    "10": "Placas, painéis e outdoors",
    "15": "Ação Comercial",
    "16": "Carro de Som",
    "18": "Loja Parque da Matriz",
    "19": "Grupo Whatsapp Local",
    "20": "Adesivação Automotiva",
    "21": "Redes Sociais",
    "23": "Indicação Funcionário",
    "26": "Melhor Plano",
    "29": "Site",
    "30": "Indicação Condomínio",
    "31": "Outros",
    "32": "Cliente viu a logo na CTO",
    "34": "Lead Fenix",
    "35": "Já foi cliente",
    "39": "Roteador no local",
    "40": "Troca de Titularidade",
    "41": "Ex-funcionário",
    "42": "Panfleto",
    "43": "Tráfego Pago",
    "44": "Loja Maloha Haussem",
    "45": "Panfleto Sinaleira",
    "46": "Facebook",
    "47": "Instagram",
}