const SELLER_MAP = {
    "48": "Eduardo Lima",
    "67": "Nicole Gahlern",
    "35": "Jonas Paixão",
    "25": "Lucas Dai Prá",
    "24": "Otávio Albano",
    "23": "Mayara Oliveira",
    "33": "Cláudia Dalcarobo",
    "16": "Barbara",
    "73": "Jenifer Costa",
    "43": "José Luiz",
    "62": "João Pedro",
    "63": "Maria Cecilia",
    "54": "Poliana Guimarães",
    "45": "Emily Goulart",
    "74": "Leandro Farias",
    "71": "Evelyn Rosa",
    "69": "Vitória Prezzi",
    "0": "Sem registro"
}